/// <reference types="next" />
/// <reference types="next/navigation-types/compat" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited directly. It is automatically generated by Next.js